### ISSUE TITLE
Stenography is not Steganography

### ISSUE THREAD

**Issue by jshprentz** [thoppe/Presentation-Black-Hack-Data-Wrangling#1]
Correct "stenography" to "steganography" in a few slides.
- _Stenography:_ the action or process of writing in shorthand or taking dictation.
- _Steganography:_ the practice of concealing messages or information within other nonsecret text or data.

Great talk tonight. Thanks.

**Comment by thoppe** [comment]
@jshprentz Thanks for fix! The slides are now slightly more correct thanks to you -- feel free to send any more comments and corrections, I'm glad you enjoyed the talk!
